spring:
  profiles: 
    active: staging

  application:
    name: authservice
    tokenExpiryTime: 300000

# Postgres configuration
  datasource:
    url: jdbc:postgresql://192.168.0.102:5432/authdb
    username: postgres
    password: nayak@rth1
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect   
    hibernate:
      ddl-auto: update                                   
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# END Postgres configuration
#redis config
  data:
    redis:
      host: 192.168.0.102
      port: 6379
      password: nayak@rth1

#END redis config

  security:
    user:
      name: admin
      password: test 

# This is main server configuration.
server:
  port: 8081
  